name: Image optimization
on:
  workflow_dispatch:
  pull_request:

jobs:
  my_bot_job:
    runs-on: ubuntu-latest
    steps:
      - uses: evansnguyen/image-optimization@v1.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          file: 'assets'
          branch: 'next-release'
          commit-branch: 'awesome/image-optimization'
